import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import Header from "@/components/Header/Header";
import Providers from "@/redux/Providers";
import { ToastContainer } from "react-toastify";

const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
    title: "Ghorer Bazar Task",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={nunitoSans.className}>
                <Providers>
                    <ToastContainer />
                    <Header />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
