import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={nunitoSans.className}>
                <Header />
                {children}
            </body>
        </html>
    );
}
